### ISSUE TITLE
Font size for each segment

### ISSUE THREAD

**Issue by rlaferla** [u10int/URBSegmentedControl#18]
I want to set the font size for each segment but there is no method to do it nor is there a way to get a segment (item) or list of segments (items).

**Comment by rlaferla** [comment]
Can you expose URBSegmentView and the method segmentAtIndex: ?  The current design is rather inflexible.  I think that would be best.  If not, add a - (void)setSegmentFont:(UIFont *)aFont atIndex:(NSUInteger)segment method.  Or a setFont: method on the top level control.

**Comment by u10int** [comment]
There was a bug with the `setTextAttribute:forState:` method I had in the class. I resolved this by using UISegmentedControl's standard `setTitleTextAttributes:forState:` method, which you can use for setting the font and font size on the segments. There's an example of this in the demo project's AppDelegate:

```
NSDictionary *textAttributes = @{UITextAttributeFont: [UIFont fontWithName:@"Avenir-Heavy" size:16.0]};
URBSegmentedControl *verticalControl2 = [[URBSegmentedControl alloc] initWithTitles:titles icons:icons];
verticalControl2.frame = CGRectMake(CGRectGetMaxX(verticalControl.frame) + 20.0, CGRectGetMaxY(iconControl.frame) + 20.0, 180.0, 150.0);
verticalControl2.layoutOrientation = URBSegmentedControlOrientationVertical;
verticalControl2.imageEdgeInsets = UIEdgeInsetsMake(6.0, 6.0, 6.0, 6.0);
[verticalControl2 setTitleTextAttributes:textAttributes forState:UIControlStateNormal];
[viewController.view addSubview:verticalControl2];
```

By design there isn't a way to set a different font for an individual segment since this is the expected behavior of UISegmentedControl. If you need different fonts per segment, then feel free to edit the implementation for your custom usage.
